### ISSUE TITLE
Crash with 'Type Mismatch' on invalid track numbers

### ISSUE THREAD

**Issue by druska** [dmitryleskov/iTunesScripts#1]
I received this error while trying to convert 1500 songs. It works fine if I remove this album, of course.

```
Found FLAC file E:\Music\FLAC Archive\Legend of Zelda - Ocarina of Time Soundtrack CD (US)\02 - Deku Tree.flac
Extracting metadata from E:\Music\FLAC Archive\Legend of Zelda - Ocarina of Time Soundtrack CD (US)\02 - Deku Tree.flac
Unrecognized meta tag: LENGTH
Unrecognized meta tag: BAND
Unrecognized meta tag: COMPOSER
Decompressing FLAC file into C:\Users\dave\AppData\Local\Temp\AddFLACs-2013-02-0
1-13-19-24\temp.wav
Converting WAV file to iTunes track
temp...0%...100% Done!
Writing metadata
C:\Users\dave\Desktop\AddFLACs-0.9\AddFLACs.js(239, 40) Microsoft JScript runtime error: Type mismatch
```

**Comment by dmitryleskov** [comment]
It seems that song has something other than an integer number in the TRACKNUMBER meta tag. It looks like I need to check values for compatibility before trying to pass them to the iTunes API.

**Comment by dmitryleskov** [comment]
@druska: I believe I've got this fixed, can you test the new AddFLACS.js against that album again?

**Comment by druska** [comment]
@dmitryleskov works great! I love squashing bugs.

**Comment by a-nd** [comment]
im getting the same error trying to add this track

Found FLAC file ...\2017-03-31 18.44.19\08.- Depeche Mode - Blue Dress.flac
Extracting metadata from ...\2017-03-31 18.44.19\08.- Depeche Mode - Blue Dress.flac
Unrecognized meta tag: DISC
Unrecognized meta tag: DISCNUMBER
Unrecognized meta tag: MUSICBRAINZ_TRACKID
Unrecognized meta tag: ALBUMARTISTSORT
Unrecognized meta tag: MUSICBRAINZ_ALBUMID
Unrecognized meta tag: MUSICBRAINZ_RELEASEGROUPID
Unrecognized meta tag: ALBUMARTIST_CREDIT
Unrecognized meta tag: TRACKTOTAL
Unrecognized meta tag: TRACKC
Unrecognized meta tag: TOTALTRACKS
Unrecognized meta tag: MUSICBRAINZ_ALBUMARTISTID
Unrecognized meta tag: BPM
Unrecognized meta tag: ARTIST_CREDIT
Unrecognized meta tag: DISCTOTAL
Unrecognized meta tag: DISCC
Unrecognized meta tag: TOTALDISCS
Unrecognized meta tag: MUSICBRAINZ_ALBUMSTATUS
Unrecognized meta tag: ALBUM ARTIST
Unrecognized meta tag: ALBUMARTIST
Unrecognized meta tag: YEAR
Unrecognized meta tag: ASIN
Unrecognized meta tag: MEDIA
Unrecognized meta tag: ARTISTSORT
Unrecognized meta tag: DESCRIPTION
Unrecognized meta tag: LABEL
Unrecognized meta tag: PUBLISHER
Unrecognized meta tag: CATALOGNUMBER
Unrecognized meta tag: ORIGINALDATE
Unrecognized meta tag: MUSICBRAINZ_ARTISTID
Unrecognized meta tag: TRACK
Unrecognized meta tag: LANGUAGE
Unrecognized meta tag: RELEASECOUNTRY
Unrecognized meta tag: SCRIPT
Unrecognized meta tag: MUSICBRAINZ_ALBUMTYPE
Decompressing FLAC file into ...\AddFLACs-2017-03-31-15-18-02\temp.wav
Converting WAV file to iTunes track
temp...2%...30%...42%...58%...71%...87% Done!
Writing metadata
...\AddFLACs.js(383, 33) Microsoft JScript runtime error: Type mismatch

it actually adds the track fine but then crashes before moving on to the next one in the folder

looks like the same thing happening but for invalid dates

**Comment by a-nd** [comment]
also this mysteriously happened despite the rest of the album working. had to remove the track to continue in the folder. 

Found FLAC file ...\Broken Social Scene\Broken Social Scene Presents Brendan Canning - Something for all of us 2008\07. Brendan Canning - Antique Bull.flac
Extracting metadata from ...\Broken Social Scene\Broken Social Scene Presents Brendan Canning - Something for all of us 2008\07. Brendan Canning - Antique Bull.flac
Decompressing FLAC file into ...\AppData\Local\Temp\AddFLACs-2017-03-31-17-28-27\temp.wav
Converting WAV file to iTunes track
 Conversion failed
...\AddFLACs.js(375, 13) Microsoft JScript runtime error: 'Location' is null or not an object

otherwise did a great job converting a big mess for me, thanks so much for this useful tool
