### ISSUE TITLE
Microsoft JScript runtime error: Type  mismatch

### ISSUE THREAD

**Issue by MediaManXL** [dmitryleskov/iTunesScripts#4]
Sorry, I'll withdraw this.  I see that the date tag must contain only year.  My apologies.

Your script had been working perfectly for me (thank you.)  I went to use it today and received an error message, which I've pasted below.  From the line referenced, it appears to be something related to the date tag on the flac file, but I don't see anything strange about the tags on these files.  It's very likely that Windows Updates have installed since the last time I ran the script successfully.  Thank you.

```
Decompressing FLAC file into C:\Users\BOBDEV~2\AppData\Local\Temp\AddFLACs-2014-
02-17-15-18-08\temp.wav
Converting WAV file to iTunes track
temp...5%...21%...46%...76% Done!
Writing metadata
E:\FLAC_SONGS_STAGING\AddFLACs.js(253, 33) Microsoft JScript runtime error: Type
 mismatch


E:\FLAC_SONGS_STAGING>
```

**Comment by dmitryleskov** [comment]
Most likely, the DATE field in those FLAC files' metadata contains a non-numeric string. It is supposed to contain a four-digit year, e.g. "1984".
